// <auto-generated />
using BobDono.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BobDono.Migrations
{
    [DbContext(typeof(BobDatabaseContext))]
    [Migration("20171001103743_ModelCreation")]
    partial class ModelCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BobDono.Models.Entities.Bracket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BracketStageId");

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("FirstWaifuId");

                    b.Property<long?>("SecondWaifuId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("BracketStageId");

                    b.HasIndex("FirstWaifuId");

                    b.HasIndex("SecondWaifuId");

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("BobDono.Models.Entities.BracketStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ElectionId");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("BracketStages");
                });

            modelBuilder.Entity("BobDono.Models.Entities.Election", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AuthorId");

                    b.Property<string>("Description");

                    b.Property<ulong>("DiscordChannelId");

                    b.Property<int>("EntrantsPerUser");

                    b.Property<string>("Name");

                    b.Property<ulong>("OpeningMessageId");

                    b.Property<DateTime>("SubmissionsEndDate");

                    b.Property<DateTime>("SubmissionsStartDate");

                    b.Property<DateTime>("VotingEndDate");

                    b.Property<DateTime>("VotingStartDate");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("BobDono.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("DiscordId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BobDono.Models.Entities.UserWaifu", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("WaifuId");

                    b.HasKey("UserId", "WaifuId");

                    b.HasIndex("WaifuId");

                    b.ToTable("UserWaifu");
                });

            modelBuilder.Entity("BobDono.Models.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BracketId");

                    b.Property<long?>("ContenderId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("ContenderId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BobDono.Models.Entities.Waifu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("MalId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Waifus");
                });

            modelBuilder.Entity("BobDono.Models.Entities.WaifuContender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomImageUrl");

                    b.Property<long?>("ElectionId");

                    b.Property<long?>("ProposerId");

                    b.Property<int>("SeedNumber");

                    b.Property<long?>("WaifuId");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ProposerId");

                    b.HasIndex("WaifuId");

                    b.ToTable("WaifuContenders");
                });

            modelBuilder.Entity("BobDono.Models.Entities.Bracket", b =>
                {
                    b.HasOne("BobDono.Models.Entities.BracketStage", "BracketStage")
                        .WithMany("Brackets")
                        .HasForeignKey("BracketStageId");

                    b.HasOne("BobDono.Models.Entities.WaifuContender", "FirstWaifu")
                        .WithMany()
                        .HasForeignKey("FirstWaifuId");

                    b.HasOne("BobDono.Models.Entities.WaifuContender", "SecondWaifu")
                        .WithMany()
                        .HasForeignKey("SecondWaifuId");
                });

            modelBuilder.Entity("BobDono.Models.Entities.BracketStage", b =>
                {
                    b.HasOne("BobDono.Models.Entities.Election", "Election")
                        .WithMany("BracketStages")
                        .HasForeignKey("ElectionId");
                });

            modelBuilder.Entity("BobDono.Models.Entities.Election", b =>
                {
                    b.HasOne("BobDono.Models.Entities.User", "Author")
                        .WithMany("Elections")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("BobDono.Models.Entities.UserWaifu", b =>
                {
                    b.HasOne("BobDono.Models.Entities.User", "User")
                        .WithMany("Waifus")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BobDono.Models.Entities.Waifu", "Waifu")
                        .WithMany("Users")
                        .HasForeignKey("WaifuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BobDono.Models.Entities.Vote", b =>
                {
                    b.HasOne("BobDono.Models.Entities.Bracket", "Bracket")
                        .WithMany()
                        .HasForeignKey("BracketId");

                    b.HasOne("BobDono.Models.Entities.WaifuContender", "Contender")
                        .WithMany("Votes")
                        .HasForeignKey("ContenderId");

                    b.HasOne("BobDono.Models.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BobDono.Models.Entities.WaifuContender", b =>
                {
                    b.HasOne("BobDono.Models.Entities.Election", "Election")
                        .WithMany("Contenders")
                        .HasForeignKey("ElectionId");

                    b.HasOne("BobDono.Models.Entities.User", "Proposer")
                        .WithMany()
                        .HasForeignKey("ProposerId");

                    b.HasOne("BobDono.Models.Entities.Waifu", "Waifu")
                        .WithMany()
                        .HasForeignKey("WaifuId");
                });
#pragma warning restore 612, 618
        }
    }
}
