// <auto-generated />
using BobDono.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BobDono.Migrations
{
    [DbContext(typeof(BobDatabaseContext))]
    partial class BobDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BobDono.Entities.Bracket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ElectionId");

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("FirstWaifuId");

                    b.Property<long?>("SecondWaifuId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("FirstWaifuId");

                    b.HasIndex("SecondWaifuId");

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("BobDono.Entities.Election", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("AuthorId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("BobDono.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BobDono.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BracketId");

                    b.Property<ulong?>("UserId");

                    b.Property<long?>("VotedWaifuId");

                    b.Property<long?>("WaifuContenderId");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("UserId");

                    b.HasIndex("VotedWaifuId");

                    b.HasIndex("WaifuContenderId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BobDono.Entities.Waifu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("MalId");

                    b.Property<string>("Name");

                    b.Property<ulong?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Waifus");
                });

            modelBuilder.Entity("BobDono.Entities.WaifuContender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ElectionId");

                    b.Property<ulong?>("ProposerId");

                    b.Property<long?>("WaifuId");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ProposerId");

                    b.HasIndex("WaifuId");

                    b.ToTable("WaifuContenders");
                });

            modelBuilder.Entity("BobDono.Entities.Bracket", b =>
                {
                    b.HasOne("BobDono.Entities.Election")
                        .WithMany("Brackets")
                        .HasForeignKey("ElectionId");

                    b.HasOne("BobDono.Entities.WaifuContender", "FirstWaifu")
                        .WithMany()
                        .HasForeignKey("FirstWaifuId");

                    b.HasOne("BobDono.Entities.WaifuContender", "SecondWaifu")
                        .WithMany()
                        .HasForeignKey("SecondWaifuId");
                });

            modelBuilder.Entity("BobDono.Entities.Election", b =>
                {
                    b.HasOne("BobDono.Entities.User", "Author")
                        .WithMany("Elections")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("BobDono.Entities.Vote", b =>
                {
                    b.HasOne("BobDono.Entities.Bracket", "Bracket")
                        .WithMany()
                        .HasForeignKey("BracketId");

                    b.HasOne("BobDono.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("BobDono.Entities.Waifu", "VotedWaifu")
                        .WithMany()
                        .HasForeignKey("VotedWaifuId");

                    b.HasOne("BobDono.Entities.WaifuContender")
                        .WithMany("Votes")
                        .HasForeignKey("WaifuContenderId");
                });

            modelBuilder.Entity("BobDono.Entities.Waifu", b =>
                {
                    b.HasOne("BobDono.Entities.User")
                        .WithMany("Waifus")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BobDono.Entities.WaifuContender", b =>
                {
                    b.HasOne("BobDono.Entities.Election")
                        .WithMany("Contenders")
                        .HasForeignKey("ElectionId");

                    b.HasOne("BobDono.Entities.User", "Proposer")
                        .WithMany()
                        .HasForeignKey("ProposerId");

                    b.HasOne("BobDono.Entities.Waifu", "Waifu")
                        .WithMany()
                        .HasForeignKey("WaifuId");
                });
#pragma warning restore 612, 618
        }
    }
}
